# =============================================================
# Xiaobai (desktop xiaobai) build script
# -------------------------------------------------------------
# .\build_exe.ps1 [-UseVenv <path>] [-UseCondaEnv <path>] [-BuildDir build] [-DistDir dist] [-SkipBuild]
# =============================================================
[CmdletBinding()]
param(
    [string]$UseVenv = "",
    [string]$UseCondaEnv = "",
    [string]$BuildDir = (Join-Path $PSScriptRoot "build"),
    [string]$DistDir  = (Join-Path $PSScriptRoot "dist"),
    [switch]$SkipBuild = $false,
    [switch]$SkipRust = $false
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot

# --- 0) Ensure Python interpreter available + inject external venv/conda env ----
if ($UseVenv -and (Test-Path $UseVenv)) {
    $env:XIAOBAI_VENV_DIR = (Resolve-Path $UseVenv).Path
    $PyExe = Join-Path $env:XIAOBAI_VENV_DIR "Scripts\python.exe"
    if (!(Test-Path $PyExe)) { $PyExe = Join-Path $env:XIAOBAI_VENV_DIR "bin/python" }
} elseif ($UseCondaEnv -and (Test-Path $UseCondaEnv)) {
    $env:XIAOBAI_VENV_DIR = (Resolve-Path $UseCondaEnv).Path
    $PyExe = Join-Path $env:XIAOBAI_VENV_DIR "python.exe"
} else {
    $PyExe = (Get-Command python).Source
}

if (!(Test-Path $PyExe)) { throw "Python interpreter not found: $PyExe" }
Write-Host "==> python = $PyExe" -ForegroundColor Cyan
& $PyExe --version

# --- 1) Install build dependencies --------------------------------------------
if (-not $SkipBuild) {
    Write-Host "==> Install PyInstaller and project (editable)" -ForegroundColor Cyan
    Push-Location $Root
    try {
        & $PyExe -m pip install --upgrade pip | Out-Null
        & $PyExe -m pip install -e ".[build]" --no-cache-dir 2>&1 | Select-Object -Last 20
    } finally {
        Pop-Location
    }
}

# --- 1a) Build Rust core extension (xiaobai_core) ---------------------------
if (-not $SkipRust) {
    $RustDir = Join-Path $Root "xiaobai_core"
    if (Test-Path (Join-Path $RustDir "Cargo.toml")) {
        Write-Host "==> Build Rust core extension (xiaobai_core)" -ForegroundColor Cyan
        Push-Location $RustDir
        try {
            & cargo build --release 2>&1 | Select-Object -Last 10
            if ($LASTEXITCODE -ne 0) {
                Write-Warning "Rust build failed (exit $LASTEXITCODE). Continuing with pure-Python fallback."
            } else {
                # Copy .pyd to package directory
                $PydSrc = Join-Path $RustDir "target\release\xiaobai_core.dll"
                $PydDst = Join-Path $Root "xiaobai_voice\xiaobai_core.pyd"
                if (Test-Path $PydSrc) {
                    Copy-Item -Force $PydSrc $PydDst
                    Write-Host "[OK] xiaobai_core.pyd copied to package" -ForegroundColor Green
                }
            }
        } finally {
            Pop-Location
        }
    } else {
        Write-Host "[skip] xiaobai_core/Cargo.toml not found, skipping Rust build" -ForegroundColor DarkGray
    }
}

# --- 2) Prepare spec / output dirs -------------------------------------------
New-Item -ItemType Directory -Force -Path $BuildDir | Out-Null
New-Item -ItemType Directory -Force -Path $DistDir  | Out-Null

# --- 2a) Generate runtime hook (2nd safety net for stdout/stderr=None in windowed mode)
$HookContent = @'
import sys, io
if sys.stdout is None:
    sys.stdout = io.StringIO()
if sys.stderr is None:
    sys.stderr = io.StringIO()
'@
$HookPath = Join-Path $BuildDir "_xiaobai_hook.py"
Set-Content -Path $HookPath -Value $HookContent -Encoding UTF8
Write-Host "[OK] runtime hook generated: $HookPath" -ForegroundColor DarkGray

# --- 2b) Normalize paths to forward slashes (avoid \U unicodeescape SyntaxError in spec)
$RootFwd  = $Root.Replace('\','/')
$RunPyFwd = (Join-Path $Root "run.py").Replace('\','/')
$HookFwd  = $HookPath.Replace('\','/')

$SpecContent = @'
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_exe.ps1. Customize by hand-maintaining .spec file if needed.
import os
from pathlib import Path
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

_ROOT = Path(r"{{ROOT}}")   # project root, forward slashes

block_cipher = None

hiddenimports = []
datas = []

# ---- Explicit resource collection (collect_data_files may miss nested yaml / top-level files) ----
# 1) xiaobai_voice/config/*.yaml (ensure default_config.yaml / models.yaml are bundled)
datas += [
    (str(_ROOT / "xiaobai_voice" / "config" / "*.yaml"), "xiaobai_voice/config"),
]
# 2) pyproject.toml: version / license info may be read from importlib.metadata or directly
datas += [
    (str(_ROOT / "pyproject.toml"), "xiaobai_voice"),
]
# 3) README.md placed at exe same level (COLLECT root)
datas += [
    (str(_ROOT / "README.md"), "."),
]
# 4) Top-level models/ dir readme files (bundle if exist)
_models_dir = _ROOT / "models"
if _models_dir.is_dir():
    for _f in _models_dir.iterdir():
        if _f.is_file():
            datas += [(str(_f), "models")]

# ---- Also attach importlib.metadata level data_files (double safety) ----
datas += collect_data_files("xiaobai_voice", include_py_files=False, excludes=["tests"])

# Common 3rd-party lib DLLs / resources
hiddenimports += collect_submodules("sherpa_onnx")
hiddenimports += collect_submodules("onnxruntime")
hiddenimports += collect_submodules("sounddevice")
hiddenimports += collect_submodules("httpx")
hiddenimports += collect_submodules("uvicorn")
hiddenimports += collect_submodules("fastapi")
hiddenimports += collect_submodules("websockets")
hiddenimports += collect_submodules("PySide6")
hiddenimports += collect_submodules("pynput")
# CosyVoice2 / Fish-S2-Pro optional; build continues even if not installed
try:
    import cosyvoice  # noqa: F401
    hiddenimports += collect_submodules("cosyvoice")
except Exception:
    pass
try:
    import fish_speech  # noqa: F401
    hiddenimports += collect_submodules("fish_speech")
except Exception:
    pass

a = Analysis(
    [r"{{RUNPY}}"],
    pathex=[str(_ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[r"{{HOOK}}"],
    excludes=[
        # Exclude interactive / dev tools from bundle
        "tkinter", "matplotlib", "pandas", "plotly", "pytest", "black", "flake8", "jupyter", "IPython",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Xiaobai",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="Xiaobai",
)
'@

# Replace placeholders with actual values
$SpecContent = $SpecContent -replace '\{\{ROOT\}\}', $RootFwd
$SpecContent = $SpecContent -replace '\{\{RUNPY\}\}', $RunPyFwd
$SpecContent = $SpecContent -replace '\{\{HOOK\}\}', $HookFwd

$SpecPath = Join-Path $BuildDir "Xiaobai.spec"
Set-Content -Path $SpecPath -Value $SpecContent -Encoding UTF8
Write-Host "[OK] spec generated: $SpecPath" -ForegroundColor DarkGray
Write-Host "    entry script: $RunPyFwd" -ForegroundColor DarkGray
Write-Host "    runtime hook: $HookFwd" -ForegroundColor DarkGray

# --- 3) Build -----------------------------------------------------------------
Push-Location $Root
try {
    Write-Host "==> PyInstaller building (slow on first run)..." -ForegroundColor Cyan
    & $PyExe -m PyInstaller --noconfirm --clean `
        --workpath (Resolve-Path $BuildDir) `
        --distpath (Resolve-Path $DistDir) `
        $SpecPath
    if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed, exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}

$Exe = Join-Path $DistDir "Xiaobai\Xiaobai.exe"
if (!(Test-Path $Exe)) { throw ("exe not found after build: " + $Exe) }
Write-Host ("OK ==> " + $Exe) -ForegroundColor Green
Write-Host ""
Write-Host "NOTE: Validate with Start-Process (no console) to catch stderr=None issues:" -ForegroundColor DarkYellow
Write-Host ("    Start-Process " + $Exe)
Write-Host ("    Start-Process " + $Exe + " -ArgumentList --selftest-full")
